const COPY = {
  libraryLead: {
    en: 'Develop your skills with curated professional learning modules',
    th: 'พัฒนาทักษะด้วยโมดูลการเรียนรู้ทางวิชาชีพที่คัดสรรแล้ว',
  },
  moduleLibrary: { en: 'Module Library', th: 'คลังโมดูล' },
  searchModule: { en: 'Search module', th: 'ค้นหาโมดูล' },
  moduleFound: { en: '{n} module found', th: 'พบ {n} โมดูล' },
  modulesFound: { en: '{n} modules found', th: 'พบ {n} โมดูล' },
  viewModules: { en: 'View modules', th: 'ดูโมดูล' },
  resume: { en: 'Resume', th: 'เรียนต่อ' },
  review: { en: 'Review', th: 'ทบทวน' },
  start: { en: 'Start', th: 'เริ่ม' },
  series: { en: 'Series', th: 'ชุดบทเรียน' },
  new: { en: 'New', th: 'ใหม่' },
  required: { en: 'Required', th: 'จำเป็น' },
  completed: { en: 'Completed', th: 'เสร็จแล้ว' },
  minutes: { en: '{n} min', th: '{n} นาที' },
  moduleCount: { en: '{n} modules', th: '{n} โมดูล' },
  modulesInSeries: { en: 'Modules in this series', th: 'โมดูลในชุดนี้' },
  downloadPdf: { en: 'Download resources (PDF)', th: 'ดาวน์โหลดเอกสาร (PDF)' },
  downloadRelated: { en: 'Download related resources', th: 'ดาวน์โหลดเอกสารที่เกี่ยวข้อง' },
  back: { en: 'Back', th: 'กลับ' },
  progress: { en: 'Progress', th: 'ความคืบหน้า' },
  sectionOf: { en: 'Section {n} of {m}', th: 'ส่วนที่ {n} จาก {m}' },
  knowledgeCheck: { en: 'Knowledge Check', th: 'แบบทดสอบความรู้' },
  questionLabel: { en: 'Q{n} Knowledge Check', th: 'คำถามที่ {n}' },
  answerFirst: {
    en: 'Answer the question below before proceeding to the next section.',
    th: 'ตอบคำถามด้านล่างก่อนไปส่วนถัดไป',
  },
  checkAnswer: { en: 'Check answer', th: 'ตรวจคำตอบ' },
  answerCorrect: { en: 'Correct', th: 'ถูกต้อง' },
  answerIncorrect: { en: 'Incorrect', th: 'ไม่ถูกต้อง' },
  continueNext: { en: 'Continue to Next Section', th: 'ไปส่วนถัดไป' },
  previous: { en: 'Previous', th: 'ก่อนหน้า' },
  next: { en: 'Next', th: 'ถัดไป' },
  keyInsight: { en: 'Key Insights', th: 'ประเด็นสำคัญ' },
  practicalTip: { en: 'Practical Tip', th: 'เคล็ดลับ' },
  moduleReview: { en: 'Module Review', th: 'ทบทวนโมดูล' },
  reviewLead: {
    en: 'Review your results below. You can retake questions to improve your score.',
    th: 'ดูผลด้านล่าง คุณสามารถทำคำถามใหม่เพื่อปรับคะแนนได้',
  },
  score: { en: 'Score', th: 'คะแนน' },
  status: { en: 'Status', th: 'สถานะ' },
  needReviewTitle: { en: 'Need Review', th: 'ควรทบทวน' },
  needsReview: { en: 'Needs review', th: 'ควรทบทวน' },
  viewAll: { en: 'View all', th: 'ดูทั้งหมด' },
  viewModulesAction: { en: 'View Modules', th: 'ดูโมดูล' },
  inProgress: { en: 'In progress', th: 'กำลังเรียน' },
  correctOf: { en: '{n}/{m} correct', th: 'ถูก {n}/{m}' },
  questionBreakdown: { en: 'Question breakdown', th: 'รายละเอียดคำถาม' },
  moreResources: { en: 'More resources', th: 'แหล่งเรียนรู้อื่น' },
  relatedTools: { en: 'Related customizers', th: 'เครื่องมือที่เกี่ยวข้อง' },
  startCreating: { en: 'Start creating', th: 'เริ่มสร้าง' },
  backToAcademy: { en: 'Back to Academy', th: 'กลับสู่สถาบันครู' },
  completeModule: { en: 'Complete Module', th: 'จบโมดูล' },
  submitReflection: { en: 'Submit Reflection', th: 'ส่งการสะท้อนคิด' },
  reflectionLead: {
    en: 'Write a brief summary of your key takeaways from this resource.',
    th: 'สรุปสิ่งที่ได้เรียนรู้จากบทเรียนนี้สั้นๆ',
  },
  yourReflection: { en: 'Your Reflection', th: 'การสะท้อนคิดของคุณ' },
  reflectionPlaceholder: {
    en: 'Summarize your key learnings, how you plan to apply these ideas, or any questions you still have...',
    th: 'สรุปสิ่งที่เรียนรู้ วิธีที่จะนำไปใช้ หรือคำถามที่ยังมี...',
  },
  reflectionHint: { en: 'Minimum a few sentences recommended', th: 'แนะนำให้เขียนอย่างน้อยสองสามประโยค' },
  characters: { en: '{n} characters', th: '{n} ตัวอักษร' },
  cancel: { en: 'Cancel', th: 'ยกเลิก' },
  submit: { en: 'Submit', th: 'ส่ง' },
  seriesComplete: { en: 'Series complete', th: 'จบชุดบทเรียนแล้ว' },
  seriesCompleteBody: {
    en: 'You have completed every module in this series. Submit your final reflection to finish.',
    th: 'คุณเรียนจบทุกโมดูลในชุดนี้แล้ว ส่งการสะท้อนคิดครั้งสุดท้ายเพื่อจบชุดบทเรียน',
  },
  submitFinal: { en: 'Submit final reflection', th: 'ส่งการสะท้อนคิดครั้งสุดท้าย' },
  seriesDoneTitle: { en: 'Series Complete!', th: 'จบชุดบทเรียนแล้ว' },
  seriesDoneBody: {
    en: "Congratulations! You've completed all modules in this series. Submit your final reflection to earn your certificate and professional development credit.",
    th: 'ยินดีด้วย คุณเรียนจบทุกโมดูลในชุดนี้แล้ว ส่งการสะท้อนคิดครั้งสุดท้ายเพื่อจบชุดบทเรียน',
  },
  moduleDoneTitle: { en: 'Module Complete!', th: 'จบโมดูลแล้ว' },
  moduleDoneBody: {
    en: "Congratulations! You've completed this module. Submit your final reflection to finish.",
    th: 'ยินดีด้วย คุณเรียนจบโมดูลนี้แล้ว ส่งการสะท้อนคิดครั้งสุดท้ายเพื่อจบ',
  },
  submitFinalReflection: { en: 'Submit Final Reflection', th: 'ส่งการสะท้อนคิดครั้งสุดท้าย' },
  downloadResourcesTitle: { en: 'Download resources', th: 'ดาวน์โหลดเอกสาร' },
  downloadResourcesLead: { en: 'Select resources you want to download', th: 'เลือกเอกสารที่ต้องการดาวน์โหลด' },
  selectAll: { en: 'Select All', th: 'เลือกทั้งหมด' },
  itemsSelected: { en: '{n} of {m} items selected', th: 'เลือก {n} จาก {m} รายการ' },
  searchResources: { en: 'Search Resources...', th: 'ค้นหาเอกสาร...' },
  downloadSelected: { en: 'Download Selected (ZIP)', th: 'ดาวน์โหลดที่เลือก (ZIP)' },
  noResources: { en: 'No resources to download.', th: 'ไม่มีเอกสารให้ดาวน์โหลด' },
  emptyLibrary: {
    en: 'No modules are published for this Academy yet.',
    th: 'ยังไม่มีโมดูลในสถาบันครูสำหรับการใช้งานนี้',
  },
  emptySearch: { en: 'No modules match that search.', th: 'ไม่พบโมดูลที่ตรงกับการค้นหา' },
  filters: { en: 'Filters', th: 'ตัวกรอง' },
  clearFilters: { en: 'Clear filters', th: 'ล้างตัวกรอง' },
  createModule: { en: 'Create module', th: 'สร้างโมดูล' },
  createSeries: { en: 'Create series', th: 'สร้างชุดบทเรียน' },
  edit: { en: 'Edit', th: 'แก้ไข' },
  save: { en: 'Save', th: 'บันทึก' },
  saving: { en: 'Saving', th: 'กำลังบันทึก' },
  loading: { en: 'Loading', th: 'กำลังโหลด' },
  forbidden: { en: 'You cannot change this Academy item.', th: 'คุณไม่สามารถแก้ไขรายการนี้ได้' },
  saveFailed: { en: 'Could not save. Check the form and try again.', th: 'บันทึกไม่สำเร็จ ตรวจสอบแบบฟอร์มแล้วลองอีกครั้ง' },
  name: { en: 'Name', th: 'ชื่อ' },
  description: { en: 'Description', th: 'คำอธิบาย' },
  cover: { en: 'Cover image URL', th: 'URL รูปปก' },
  duration: { en: 'Duration (minutes)', th: 'ระยะเวลา (นาที)' },
  english: { en: 'English', th: 'ภาษาอังกฤษ' },
  thai: { en: 'Thai', th: 'ภาษาไทย' },
  sections: { en: 'Sections', th: 'ส่วน' },
  addSection: { en: 'Add section', th: 'เพิ่มส่วน' },
  addBlock: { en: 'Add block', th: 'เพิ่มบล็อก' },
  remove: { en: 'Remove', th: 'ลบ' },
  checkPrompt: { en: 'Knowledge check prompt', th: 'คำถามแบบทดสอบ' },
  correctOption: { en: 'Correct option', th: 'ตัวเลือกที่ถูก' },
  reflection: { en: 'Reflection', th: 'การสะท้อนคิด' },
  none: { en: 'None', th: 'ไม่มี' },
  textResponse: { en: 'Written response', th: 'คำตอบแบบเขียน' },
  choiceResponse: { en: 'Single choice', th: 'ตัวเลือกเดียว' },
  downloads: { en: 'Downloads', th: 'ไฟล์ดาวน์โหลด' },
  related: { en: 'Related module ids', th: 'รหัสโมดูลที่เกี่ยวข้อง' },
  tools: { en: 'Related tools', th: 'เครื่องมือที่เกี่ยวข้อง' },
  moduleIds: { en: 'Module ids, one per line, in order', th: 'รหัสโมดูล หนึ่งรหัสต่อบรรทัด ตามลำดับ' },
  tags: { en: 'Tags', th: 'แท็ก' },
  tagHint: {
    en: 'Topic, type, and Required use the same tagging dialog as student content.',
    th: 'หัวข้อ ประเภท และรายการจำเป็น ใช้หน้าต่างแท็กเดียวกับเนื้อหาของนักเรียน',
  },
  savedTags: { en: 'Tag this item', th: 'ติดแท็กรายการนี้' },
  playFailed: { en: 'Could not save your progress.', th: 'บันทึกความคืบหน้าไม่สำเร็จ' },
  sampleNote: {
    en: 'Sample modules are only in this browser. They are not saved to the platform.',
    th: 'โมดูลตัวอย่างอยู่แค่ในเบราว์เซอร์นี้ และไม่ได้ถูกบันทึกลงแพลตฟอร์ม',
  },
  notFound: { en: 'That Academy item is not available.', th: 'ไม่พบรายการนี้ในสถาบันครู' },
  noScore: { en: 'No knowledge checks', th: 'ไม่มีแบบทดสอบ' },
}

export function academyCopy(lang, slug, vars) {
  const short = String(lang || 'en').split(/[-_]/)[0].toLowerCase()
  const entry = COPY[slug]
  if (!entry) return slug
  let text = (typeof entry[short] === 'string' && entry[short]) || entry.en || slug
  if (vars) {
    for (const [key, value] of Object.entries(vars)) {
      text = text.replaceAll(`{${key}}`, String(value))
    }
  }
  return text
}
